module.exports = [
  "Accessibility",
  "Animation",
  "Buttons",
  "Container Queries",
  "Custom Properties",
  "Design",
  "Flexbox",
  "Forms",
  "Grid",
  "Images",
  "Layout",
  "Pseudo Elements",
  "Responsive Design",
  "Resources",
  "Selectors",
  "Typography",
];
